#!/bin/sh

git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh 

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
# cd "$HOME"
# echo "Init submodules"
# yadm submodule update --recursive --init
